server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/korus_db?options=-c%20timezone=UTC
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  exposed:
    generate-ddl: true