POST http://localhost:8080/api/transactions
Content-Type: application/json

{
  "title": "Supermercado",
  "amount": 4500.00,
  "type": "EXPENSE",
  "category": "FOOD"
}

###
POST http://localhost:8080/api/transactions
Content-Type: application/json

{
  "title": "Bondi",
  "amount": 450.00,
  "type": "EXPENSE",
  "category": "TRANSPORT"
}

###
POST http://localhost:8080/api/transactions
Content-Type: application/json

{
  "title": "Avion",
  "amount": 0.0,
  "type": "EXPENSE",
  "category": "TRANSPORT"
}

###
POST http://localhost:8080/api/transactions
Content-Type: application/json

{
  "title": "",
  "amount": 234.0,
  "type": "EXPENSE",
  "category": "TRANSPORT"
}

### add income
POST http://localhost:8080/api/transactions
Content-Type: application/json

{
  "title": "Salary",
  "amount": 1500.0,
  "type": "INCOME",
  "category": "OTHERS"
}

